[tool.poetry]
name = "missing"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
intreehooks = "*"
pytest-runner = "*"
setuptools_scm = {version = "*", extras = ["toml"]}
